./my_tests.sh tests/test1
./my_tests.sh tests/test2
./my_tests.sh tests/test3
./my_tests.sh tests/test4
./my_tests.sh tests/test5
./my_tests.sh tests/test6
./my_tests.sh tests/test7
./my_tests.sh tests/test8
./my_tests.sh tests/test9
./my_tests.sh tests/test10
./my_tests.sh tests/test11
./my_tests.sh tests/test12
./my_tests.sh tests/test13
./my_tests.sh tests/test14
./my_tests.sh tests/test15
./my_tests.sh tests/test16
./my_tests.sh tests/test17
./my_tests.sh tests/test18
./my_tests.sh tests/test19
./my_tests.sh tests/test20
./my_tests.sh tests/test21
./my_tests.sh tests/test22
./my_tests.sh tests/test23
./my_tests.sh tests/test24
./my_tests.sh tests/test25