name: Check if the app builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install the ncurses
        run: sudo apt-get install --yes libncurses5-dev libncursesw5-dev
      - name: Build with Makefile
        run: make fclean && make clean && make re && make