name: Run functional tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install the ncurses
        run: sudo apt-get install --yes libncurses5-dev libncursesw5-dev
      - name: Build with Makefile & Execute tests
        run: make func