name: Run unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install the ncurses
        run: sudo apt-get install --yes libncurses5-dev libncursesw5-dev
      - name: Install Criterion
        run: sudo add-apt-repository ppa:snaipewastaken/ppa &&
          sudo apt-get update &&
          sudo apt-get install --yes criterion-dev
      - name: Install Gcovr
        run: python -m pip install --upgrade pip gcovr
      - name: Build with Makefile
        run: make tests_run
      - name: Execute tests
        run: ./unit_tests
      - name: Output coverage
        run: gcovr -e tests/